### ISSUE TITLE
HIBP API Parsing- Where to pull emails from

### ISSUE THREAD

**Issue by b4cktr4ck2** [JackEnders/SeleniumLinkedinScraper#1]
Hey man,

I've got a Python script already for polling HIBP's API against a list of emails pulled from an excel workbook, funny enough. 

I was hoping to make a pull request to add this functionality in, but I'm not sure if your script pulls the emails yet from the LinkedIn profile. If you want, I can help out with the HIBP polling once the emails are pulled from LinkedIn?

**Comment by JackEnders** [comment]
Sweet! I have to get around to the email part, but I'll ping you once it's working, that'd be great!

**Comment by b4cktr4ck2** [comment]
Awesome, I'll close this for now.
